/**
 * Roadmap content: subjects -> phases (Foundations/Core/Advanced) -> topics.
 * Each topic: { id, name, what, hitScore, why, resource: { label, url } | null }
 * `what` is a plain definition (what the technique actually is); `why` is the motivation
 * (why it matters for ICPC). `hitScore` (1-5, see HIT_SCORE_META in roadmap.js) is how
 * important the topic is for ICPC specifically — weighing both how often it's a prerequisite
 * for other topics on this list and how often it appears in regionals/World Finals directly.
 * `id` must be globally unique (subject.topic-slug) since it's the localStorage key for
 * checkbox state.
 */
const ROADMAP = [
  {
    id: "math",
    name: "Math & Number Theory",
    blurb: "Modular arithmetic, combinatorics, and the algebraic tools that show up in nearly every contest.",
    phases: [
      {
        name: "Foundations",
        topics: [
          {
            id: "math.modular-arithmetic",
            name: "Modular arithmetic & fast exponentiation",
            what: "Arithmetic where numbers wrap around a fixed modulus, and fast exponentiation computes a^b mod m in O(log b) via repeated squaring instead of b multiplications.",
            hitScore: 5,
            why: "Almost every counting or DP answer must be reduced mod 1e9+7 — fast exponentiation (and modular inverse) makes that reduction possible in O(log n).",
            resource: { label: "cp-algorithms: Binary Exponentiation", url: "https://cp-algorithms.com/algebra/binary-exp.html" },
          },
          {
            id: "math.gcd-extended-euclid",
            name: "GCD, LCM & Extended Euclid",
            what: "The Euclidean algorithm finds gcd(a,b) in O(log min(a,b)); its extended version also finds integers x,y with ax+by=gcd(a,b).",
            hitScore: 4,
            why: "Extended Euclid gives you modular inverses and solves linear Diophantine equations — a building block for half of number theory.",
            resource: { label: "cp-algorithms: Extended Euclidean Algorithm", url: "https://cp-algorithms.com/algebra/extended-euclid-algorithm.html" },
          },
          {
            id: "math.sieve-factorization",
            name: "Sieve of Eratosthenes & prime factorization",
            what: "Marks every multiple of each prime up to n in one pass, giving you every number's primality and smallest prime factor in O(n log log n).",
            hitScore: 4,
            why: "Precomputing primes/factorizations in O(n log log n) turns \"is this prime?\" from a bottleneck into a non-issue.",
            resource: { label: "cp-algorithms: Sieve of Eratosthenes", url: "https://cp-algorithms.com/algebra/sieve-of-eratosthenes.html" },
          },
          {
            id: "math.basic-combinatorics",
            name: "Combinatorics basics (permutations, combinations, Pascal's triangle)",
            what: "Counting how many ways to arrange or choose items — permutations (order matters), combinations (order doesn't), and the Pascal's-triangle recurrence for binomial coefficients.",
            hitScore: 4,
            why: "Counting arrangements and selections is one of the most common Div2 B/C problem shapes.",
            resource: { label: "cp-algorithms: Binomial Coefficients", url: "https://cp-algorithms.com/combinatorics/binomial-coefficients.html" },
          },
        ],
      },
      {
        name: "Core",
        topics: [
          {
            id: "math.modular-combinatorics",
            name: "Modular combinatorics (factorial precompute, nCr mod p)",
            what: "Precomputes factorials and inverse factorials mod p once so any nCr mod p query afterward is a single O(1) lookup.",
            hitScore: 4,
            why: "O(n) precompute then O(1) nCr mod p is a building block you'll reuse in dozens of problems.",
            resource: { label: "cp-algorithms: Factorial modulo p", url: "https://cp-algorithms.com/algebra/factorial-modulo.html" },
          },
          {
            id: "math.inclusion-exclusion",
            name: "Inclusion-exclusion principle",
            what: "Counts a union of overlapping sets by adding the individual sets, subtracting pairwise intersections, adding back triple intersections, and so on.",
            hitScore: 3,
            why: "Counts \"at least one property holds\" by adding and subtracting overlapping cases — the standard tool behind derangements, coprime-counting, and constraint-violation counting problems.",
            resource: { label: "cp-algorithms: The Inclusion-Exclusion Principle", url: "https://cp-algorithms.com/combinatorics/inclusion-exclusion.html" },
          },
          {
            id: "math.crt",
            name: "Chinese Remainder Theorem",
            what: "Given several equations of the form x ≡ a (mod m), reconstructs the unique x (mod the product of the moduli) that satisfies all of them at once.",
            hitScore: 2,
            why: "Combines several modular constraints into one — shows up whenever a problem gives you multiple \"x ≡ a (mod m)\" facts.",
            resource: { label: "cp-algorithms: Chinese Remainder Theorem", url: "https://cp-algorithms.com/algebra/chinese-remainder-theorem.html" },
          },
          {
            id: "math.totient",
            name: "Euler's totient & multiplicative functions",
            what: "Euler's totient function φ(n) counts integers up to n that are coprime to n; it and related multiplicative functions let you compute divisor-based sums efficiently via their prime factorization.",
            hitScore: 2,
            why: "Counting coprime pairs and divisor-sum problems almost always route through phi or a related multiplicative function.",
            resource: { label: "cp-algorithms: Euler's totient function", url: "https://cp-algorithms.com/algebra/phi-function.html" },
          },
          {
            id: "math.probability-ev",
            name: "Probability & expected value (linearity of expectation)",
            what: "Expected value is the probability-weighted average outcome, and linearity of expectation lets you add up expectations of simple parts even when those parts aren't independent.",
            hitScore: 3,
            why: "Linearity of expectation lets you sum the expectations of simple sub-events instead of modeling an entire complex process.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
          {
            id: "math.matrix-exponentiation",
            name: "Matrix exponentiation",
            what: "Represents a linear recurrence as a matrix, then uses fast exponentiation on the matrix itself to jump n steps ahead in O(log n) instead of computing every intermediate term.",
            hitScore: 3,
            why: "Turns an O(n) linear recurrence (Fibonacci-like DP) into O(log n) by expressing the transition as a matrix power.",
            resource: { label: "cp-algorithms: Binary Exponentiation", url: "https://cp-algorithms.com/algebra/binary-exp.html" },
          },
          {
            id: "math.game-theory-nim",
            name: "Game theory: Nim & Sprague-Grundy",
            what: "Nim is the classic take-turns-removing-objects game solved by XOR-ing pile sizes; Sprague-Grundy generalizes this to any impartial game by assigning each position a single ‘Grundy number’.",
            hitScore: 2,
            why: "Reduces a huge class of impartial two-player games to computing one XOR of Grundy numbers.",
            resource: { label: "cp-algorithms: Sprague-Grundy theorem, Nim", url: "https://cp-algorithms.com/game_theory/sprague-grundy-nim.html" },
          },
        ],
      },
      {
        name: "Advanced",
        topics: [
          {
            id: "math.fft-ntt",
            name: "FFT / NTT (fast polynomial multiplication)",
            what: "The Fast Fourier Transform converts a polynomial between coefficient and point-value form in O(n log n), which multiplies two polynomials (or convolves two arrays) far faster than the naive O(n²) way; NTT is the same idea done in modular arithmetic.",
            hitScore: 2,
            why: "Multiplies two polynomials (or computes a big convolution) in O(n log n) instead of the naive O(n²), unlocking a whole class of counting problems.",
            resource: { label: "cp-algorithms: Fast Fourier transform", url: "https://cp-algorithms.com/algebra/fft.html" },
          },
          {
            id: "math.generating-functions",
            name: "Generating functions",
            what: "Encodes a sequence as the coefficients of a formal power series, so combinatorial operations (choosing, repeating, combining) become algebraic operations (multiplying, composing) on the series.",
            hitScore: 1,
            why: "Recasts combinatorial recurrences as algebra on power series, so you can extract a coefficient instead of hand-deriving a recurrence.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
          {
            id: "math.xor-basis",
            name: "Linear algebra over GF(2) / XOR basis",
            what: "A set of numbers reduced to a linearly-independent basis under XOR (Gaussian elimination over GF(2)), so you can quickly test what values are reachable via XOR of a subset or find the maximum such value.",
            hitScore: 2,
            why: "The standard tool for \"maximum XOR subset\" and testing linear independence of a set of numbers (same Gaussian-elimination idea, applied over GF(2)).",
            resource: { label: "cp-algorithms: Gauss & System of Linear Equations", url: "https://cp-algorithms.com/linear_algebra/linear-system-gauss.html" },
          },
          {
            id: "math.mobius",
            name: "Möbius function & multiplicative-function sums",
            what: "The Möbius function μ(n) is a ±1/0-valued multiplicative function that lets inclusion-exclusion over divisors be written as one clean summation formula.",
            hitScore: 1,
            why: "Powers advanced divisor-sum and gcd-counting problems that show up at Div1 D+ / World Finals level.",
            resource: { label: "cp-algorithms: Number of divisors / sum of divisors", url: "https://cp-algorithms.com/algebra/divisors.html" },
          },
        ],
      },
    ],
  },
  {
    id: "ds",
    name: "Data Structures",
    blurb: "From arrays and DSU up through segment trees and persistent structures.",
    phases: [
      {
        name: "Foundations",
        topics: [
          {
            id: "ds.stl-basics",
            name: "C++ STL essentials (vector, pair, set/map, sort & built-in algorithms)",
            what: "The C++ Standard Template Library's ready-made containers (vector, pair, set, map) and algorithms (sort, lower_bound) that most contest code is built on top of.",
            hitScore: 5,
            why: "Contest code lives and dies by fluent STL use — knowing which container or <algorithm> call to reach for turns a 20-line manual implementation into one line.",
            resource: { label: "USACO Guide: Introduction to Data Structures", url: "https://usaco.guide/bronze/intro-ds" },
          },
          {
            id: "ds.arrays-prefix-sums",
            name: "Arrays, prefix sums & difference arrays",
            what: "A prefix-sum array stores running totals so any range sum is one subtraction; a difference array does the reverse, turning range updates into two point updates.",
            hitScore: 5,
            why: "O(1) range-sum and range-update after O(n) prep is the cheapest speedup you'll ever add to a solution.",
            resource: { label: "USACO Guide: Prefix Sums", url: "https://usaco.guide/silver/prefix-sums" },
          },
          {
            id: "ds.stacks-queues-monotonic",
            name: "Stacks, queues & monotonic stack/queue",
            what: "Stacks (last-in-first-out) and queues (first-in-first-out) are the base containers; a monotonic stack/queue keeps its elements sorted as you push, discarding ones that can never be the answer again.",
            hitScore: 4,
            why: "Linear-time solutions to \"next greater element\" and sliding-window-minimum problems, where the naive approach is O(n²).",
            resource: { label: "cp-algorithms: Minimum Stack / Minimum Queue", url: "https://cp-algorithms.com/data_structures/stack_queue_modification.html" },
          },
          {
            id: "ds.priority-queue",
            name: "Priority queue / heap",
            what: "A heap-backed container that always gives you the current minimum or maximum element in O(log n) per insert/remove.",
            hitScore: 5,
            why: "The default structure whenever you need repeated access to the current min/max — Dijkstra, Huffman-style greedy, and k-way merge all build on it.",
            resource: { label: "USACO Guide: Priority Queues", url: "https://usaco.guide/silver/priority-queues" },
          },
          {
            id: "ds.dsu",
            name: "Disjoint Set Union (DSU)",
            what: "Disjoint Set Union tracks a partition of elements into groups, answering ‘are these two connected?’ and ‘merge these two groups’ in near-O(1) amortized time via union-by-rank and path compression.",
            hitScore: 5,
            why: "Near-O(1) amortized connectivity queries — the backbone of Kruskal's MST and countless offline graph tricks.",
            resource: { label: "cp-algorithms: Disjoint Set Union", url: "https://cp-algorithms.com/data_structures/disjoint_set_union.html" },
          },
        ],
      },
      {
        name: "Core",
        topics: [
          {
            id: "ds.fenwick",
            name: "Binary Indexed Tree (Fenwick tree)",
            what: "A Fenwick (Binary Indexed) tree stores partial sums at indices determined by the lowest set bit, supporting point updates and prefix-sum queries in O(log n) each with a compact array-based implementation.",
            hitScore: 4,
            why: "A compact O(log n) structure for prefix sums with point updates — shorter and less error-prone to code under contest pressure than a segment tree.",
            resource: { label: "cp-algorithms: Fenwick Tree", url: "https://cp-algorithms.com/data_structures/fenwick.html" },
          },
          {
            id: "ds.segment-tree",
            name: "Segment tree (range query, point update)",
            what: "A binary tree over an array where each node stores an aggregate (sum/min/max/etc.) of a range, answering any range query and point update in O(log n).",
            hitScore: 5,
            why: "The single most reusable data structure in competitive programming — range min/max/sum/gcd with point updates.",
            resource: { label: "cp-algorithms: Segment Tree", url: "https://cp-algorithms.com/data_structures/segment_tree.html" },
          },
          {
            id: "ds.lazy-propagation",
            name: "Lazy propagation (range updates on segment trees)",
            what: "Stores a pending update at a segment-tree node instead of applying it to every leaf immediately, pushing it down only when a later query actually needs to look inside that node.",
            hitScore: 4,
            why: "Defers pending range updates onto child nodes only when needed, turning O(n) range updates into O(log n) — without it, a segment tree only supports point updates.",
            resource: { label: "cp-algorithms: Segment Tree", url: "https://cp-algorithms.com/data_structures/segment_tree.html" },
          },
          {
            id: "ds.sparse-table",
            name: "Sparse tables (RMQ)",
            what: "Precomputes the answer for every range whose length is a power of two, so any idempotent range query (min/max/gcd) on a static array can be answered in O(1) by combining two overlapping precomputed ranges.",
            hitScore: 3,
            why: "O(1) answers to idempotent range queries (min/max/gcd) on a static array after O(n log n) preprocessing.",
            resource: { label: "cp-algorithms: Sparse Table", url: "https://cp-algorithms.com/data_structures/sparse-table.html" },
          },
          {
            id: "ds.ordered-set",
            name: "Ordered set / order statistics (PBDS)",
            what: "A balanced-BST-backed set (GNU PBDS in C++) that adds ‘find the k-th smallest element’ and ‘find the rank of x’ on top of the usual insert/erase/find.",
            hitScore: 3,
            why: "Answers \"k-th smallest\" and \"rank of x\" queries in O(log n) — a frequent need a plain set/map can't give you.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
          {
            id: "ds.sqrt-decomp-mo",
            name: "Sqrt decomposition & Mo's algorithm",
            what: "Splits an array into √n-sized blocks so range queries touch only O(√n) blocks; Mo's algorithm reorders offline queries by block to answer them all with amortized O(√n) work each.",
            hitScore: 2,
            why: "A general-purpose O((n+q)√n) fallback for range problems that resist a clean segment-tree structure.",
            resource: { label: "cp-algorithms: Sqrt Decomposition", url: "https://cp-algorithms.com/data_structures/sqrt_decomposition.html" },
          },
        ],
      },
      {
        name: "Advanced",
        topics: [
          {
            id: "ds.persistent-segtree",
            name: "Persistent segment trees",
            what: "Each update creates new nodes only along the path that changed, so every past version of the structure stays queryable — the standard way to answer ‘k-th smallest in this range, as of this point in time’.",
            hitScore: 2,
            why: "Lets you query every historical version of an array — the standard trick for \"k-th smallest in a range, using only values up to some bound over time\".",
            resource: { label: "USACO Guide: Persistent Data Structures", url: "https://usaco.guide/adv/persistent" },
          },
          {
            id: "ds.segtree-beats",
            name: "Segment tree beats / advanced lazy tricks",
            what: "Extends lazy segment trees with an extra pruning condition so range chmin/chmax updates (not just add/assign) can still be applied in amortized O(log n).",
            hitScore: 1,
            why: "Handles range chmin/chmax-with-sum problems that plain lazy propagation can't express.",
            resource: { label: "USACO Guide: Advanced Segment Tree Techniques", url: "https://usaco.guide/adv/segtree-beats" },
          },
          {
            id: "ds.merge-sort-tree",
            name: "Merge sort tree / wavelet tree",
            what: "A segment tree whose nodes each store their range's elements in sorted order (built like merge sort), enabling offline range rank/counting queries via binary search inside each node.",
            hitScore: 2,
            why: "Offline range k-th-smallest and range-counting queries beyond what a plain segment tree can answer.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
          {
            id: "ds.link-cut-tree",
            name: "Link-cut trees",
            what: "A balanced-tree-based structure that supports cutting and linking edges of a forest while still answering path/connectivity queries in amortized O(log n).",
            hitScore: 1,
            why: "Rare, but decisive for dynamic-tree connectivity/path problems that occasionally appear at World Finals level.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
        ],
      },
    ],
  },
  {
    id: "graphs",
    name: "Graphs",
    blurb: "Traversal, shortest paths, connectivity, and flow/matching.",
    phases: [
      {
        name: "Foundations",
        topics: [
          {
            id: "graphs.bfs-dfs",
            name: "BFS/DFS & connected components",
            what: "Breadth-first search explores a graph layer by layer (shortest paths in unweighted graphs); depth-first search dives down one branch before backtracking — together they find connected components and underlie nearly every other graph technique.",
            hitScore: 5,
            why: "The traversal every other graph algorithm is built on top of.",
            resource: { label: "cp-algorithms: Breadth First Search", url: "https://cp-algorithms.com/graph/breadth-first-search.html" },
          },
          {
            id: "graphs.tree-basics",
            name: "Tree basics (rooting, DFS order, diameter)",
            what: "Picking a root, then computing each node's parent/depth/subtree-size via DFS, plus a tree's diameter (longest path) — the setup every tree-DP and tree-query technique starts from.",
            hitScore: 4,
            why: "Rooting a tree and computing DFS in/out times and diameter are the building blocks every tree-DP and tree-query technique below assumes you already have.",
            resource: { label: "USACO Guide: Introduction to Tree Algorithms", url: "https://usaco.guide/silver/intro-tree" },
          },
          {
            id: "graphs.topo-sort",
            name: "Topological sort",
            what: "Orders the vertices of a DAG so every edge points from an earlier vertex to a later one, which is what lets you process dependencies (and run DP) in a valid order.",
            hitScore: 4,
            why: "Orders tasks by dependency — a prerequisite for almost all DAG dynamic programming.",
            resource: { label: "cp-algorithms: Topological Sorting", url: "https://cp-algorithms.com/graph/topological-sort.html" },
          },
          {
            id: "graphs.dijkstra",
            name: "Dijkstra's algorithm",
            what: "A priority-queue-driven shortest-path algorithm that always expands the closest unvisited vertex next, finding all shortest paths from a source in O((V+E) log V) as long as no edge weight is negative.",
            hitScore: 5,
            why: "The default shortest-path algorithm whenever edge weights are non-negative.",
            resource: { label: "cp-algorithms: Dijkstra", url: "https://cp-algorithms.com/graph/dijkstra.html" },
          },
        ],
      },
      {
        name: "Core",
        topics: [
          {
            id: "graphs.bellman-ford",
            name: "Bellman-Ford (negative weights, cycle detection)",
            what: "Relaxes every edge up to V−1 times to find shortest paths even with negative edge weights, and one extra pass reveals whether a negative cycle exists.",
            hitScore: 3,
            why: "Handles negative edge weights and detects negative cycles, which Dijkstra silently gets wrong on.",
            resource: { label: "cp-algorithms: Bellman-Ford", url: "https://cp-algorithms.com/graph/bellman_ford.html" },
          },
          {
            id: "graphs.floyd-warshall",
            name: "Floyd-Warshall (all-pairs shortest paths)",
            what: "A triple-nested-loop DP that computes shortest paths between every pair of vertices at once in O(V³), by considering each vertex in turn as an allowed intermediate stop.",
            hitScore: 3,
            why: "A simple O(n³) all-pairs solution that's hard to beat for small, dense graphs.",
            resource: { label: "cp-algorithms: Floyd-Warshall", url: "https://cp-algorithms.com/graph/all-pair-shortest-path-floyd-warshall.html" },
          },
          {
            id: "graphs.01-bfs",
            name: "0-1 BFS & multi-source BFS",
            what: "A BFS variant using a deque instead of a queue — push 0-weight edges to the front and 1-weight edges to the back — that finds shortest paths in O(V+E) when every edge costs 0 or 1.",
            hitScore: 3,
            why: "A deque-based BFS variant that handles 0/1 edge weights in O(V+E), and multi-source BFS answers \"distance to the nearest of many sources\" without a separate run per source.",
            resource: { label: "cp-algorithms: 0-1 BFS", url: "https://cp-algorithms.com/graph/01_bfs.html" },
          },
          {
            id: "graphs.flow-basics",
            name: "Flow networks & Ford-Fulkerson / Edmonds-Karp",
            what: "A flow network has edge capacities; Ford-Fulkerson repeatedly finds an augmenting path from source to sink in the residual graph and pushes flow along it until none remain, and the final flow equals the min cut.",
            hitScore: 3,
            why: "Introduces residual graphs and augmenting paths — the mental model every faster max-flow algorithm (including Dinic's, below) builds on, and often fast enough on its own for regional-sized inputs.",
            resource: { label: "cp-algorithms: Ford-Fulkerson and Edmonds-Karp", url: "https://cp-algorithms.com/graph/edmonds_karp.html" },
          },
          {
            id: "graphs.mst",
            name: "Minimum spanning tree (Kruskal / Prim)",
            what: "A minimum spanning tree connects every vertex with the least total edge weight; Kruskal's sorts edges and adds them via DSU, Prim's grows the tree greedily from a start vertex.",
            hitScore: 4,
            why: "A classic greedy-plus-DSU pattern that also underlies many \"connect everything at minimum total cost\" problems.",
            resource: { label: "cp-algorithms: MST - Kruskal", url: "https://cp-algorithms.com/graph/mst_kruskal.html" },
          },
          {
            id: "graphs.bridges-articulation",
            name: "Bridges & articulation points",
            what: "A bridge is an edge (and an articulation point a vertex) whose removal disconnects the graph — found in one DFS pass by comparing each node's discovery time against the lowest time reachable from its subtree.",
            hitScore: 3,
            why: "Finds the edges/vertices whose removal disconnects the graph — common in network-robustness problems.",
            resource: { label: "cp-algorithms: Finding Bridges", url: "https://cp-algorithms.com/graph/bridge-searching.html" },
          },
          {
            id: "graphs.scc",
            name: "Strongly connected components (Tarjan / Kosaraju)",
            what: "A strongly connected component is a maximal set of vertices each reachable from every other; Tarjan's and Kosaraju's algorithms find all of them in one or two DFS passes, collapsing a directed graph into a DAG of SCCs.",
            hitScore: 3,
            why: "Condenses a directed graph into a DAG of SCCs, which you can then run DAG-DP over.",
            resource: { label: "cp-algorithms: Strongly Connected Components", url: "https://cp-algorithms.com/graph/strongly-connected-components.html" },
          },
          {
            id: "graphs.lca",
            name: "LCA with binary lifting",
            what: "The lowest common ancestor of two nodes is the deepest node that's an ancestor of both; binary lifting precomputes each node's 2^k-th ancestor so any LCA query resolves in O(log n).",
            hitScore: 4,
            why: "O(log n) ancestor and distance queries on a tree power a huge share of tree-DP and tree-path problems.",
            resource: { label: "cp-algorithms: LCA - Binary Lifting", url: "https://cp-algorithms.com/graph/lca_binary_lifting.html" },
          },
          {
            id: "graphs.functional-graphs",
            name: "Functional graphs (successor graphs & cycle detection)",
            what: "A graph where every node has exactly out-degree 1 (each node ‘points to’ one other), which always looks like a set of chains feeding into cycles — binary lifting answers ‘where do you end up after k steps’ in O(log k).",
            hitScore: 2,
            why: "Every node has exactly one outgoing edge (\"i points to f(i)\"), so the graph is just chains leading into cycles — the same binary-lifting idea from LCA answers \"where do I end up after k steps?\" in O(log k).",
            resource: { label: "USACO Guide: Introduction to Functional Graphs", url: "https://usaco.guide/silver/func-graphs" },
          },
          {
            id: "graphs.euler-path",
            name: "Euler path & circuit (Hierholzer's algorithm)",
            what: "A walk that uses every edge of a graph exactly once; Hierholzer's algorithm constructs one in O(E) by stitching together cycles found via DFS, once you've confirmed one exists via each vertex's degree parity.",
            hitScore: 2,
            why: "Finds a walk that uses every edge exactly once — the classic \"draw this graph without lifting your pen\" problem, and a recurring ICPC set-piece.",
            resource: { label: "cp-algorithms: Finding the Eulerian path", url: "https://cp-algorithms.com/graph/euler_path.html" },
          },
        ],
      },
      {
        name: "Advanced",
        topics: [
          {
            id: "graphs.max-flow",
            name: "Max flow (Dinic's algorithm)",
            what: "The maximum amount of flow that can be pushed from source to sink without exceeding any edge's capacity; Dinic's algorithm finds it in O(V²E) by repeatedly building level graphs and finding blocking flows.",
            hitScore: 3,
            why: "A surprising number of \"hard\" ICPC problems are secretly a max-flow problem once you find the right model.",
            resource: { label: "cp-algorithms: Dinic's algorithm", url: "https://cp-algorithms.com/graph/dinic.html" },
          },
          {
            id: "graphs.mcmf",
            name: "Min-cost max-flow",
            what: "Finds the maximum flow (or a flow of a given size) that has the smallest possible total cost, by always augmenting along the cheapest available path (e.g. via Bellman-Ford or Johnson's reweighting + Dijkstra).",
            hitScore: 2,
            why: "Extends flow modeling to problems with a cost objective, not just a feasibility/capacity one.",
            resource: { label: "cp-algorithms: Minimum-cost flow", url: "https://cp-algorithms.com/graph/min_cost_flow.html" },
          },
          {
            id: "graphs.bipartite-matching",
            name: "Bipartite matching (Kuhn's algorithm / Hopcroft-Karp)",
            what: "Finds the largest set of edges in a bipartite graph with no shared endpoints — Kuhn's algorithm repeatedly looks for an augmenting path per left vertex; Hopcroft-Karp finds many augmenting paths per phase for a faster O(E√V).",
            hitScore: 3,
            why: "Assignment-style problems (match workers to jobs, etc.) appear constantly in regional-level sets.",
            resource: { label: "cp-algorithms: Kuhn's Maximum Bipartite Matching", url: "https://cp-algorithms.com/graph/kuhn_maximum_bipartite_matching.html" },
          },
          {
            id: "graphs.two-sat",
            name: "2-SAT",
            what: "Solves boolean formulas made of clauses like (a OR b) by turning each variable into two graph nodes (true/false) with implication edges, then reading the answer off from which SCC each node lands in.",
            hitScore: 2,
            why: "Turns boolean-constraint problems (\"at least one of A or B must hold\") into an SCC computation you already know.",
            resource: { label: "cp-algorithms: 2-SAT", url: "https://cp-algorithms.com/graph/2SAT.html" },
          },
          {
            id: "graphs.hld",
            name: "Heavy-light decomposition",
            what: "Decomposes a tree into chains such that any root-to-node path crosses at most O(log n) chains, letting a segment tree over the chains answer path queries/updates in O(log² n).",
            hitScore: 2,
            why: "Path queries and updates on a tree in O(log² n) — a World-Finals-tier technique built on top of segment trees.",
            resource: { label: "cp-algorithms: Heavy-light decomposition", url: "https://cp-algorithms.com/graph/hld.html" },
          },
          {
            id: "graphs.centroid-decomposition",
            name: "Centroid decomposition",
            what: "Repeatedly removes each subtree's centroid (a node whose removal leaves no piece bigger than half the subtree) and recurses on the pieces, building a decomposition of depth O(log n) that's ideal for answering path-counting queries.",
            hitScore: 2,
            why: "Recursively splits a tree at its centroid to answer path-counting/path-query problems in O(n log n) total — a staple of Div1 E/F tree problems.",
            resource: { label: "USACO Guide: Centroid Decomposition", url: "https://usaco.guide/plat/centroid" },
          },
          {
            id: "graphs.small-to-large",
            name: "Small-to-large merging (DSU on tree)",
            what: "When merging each node's child data into a combined set, always merge the smaller child sets into the largest one — this simple rule keeps total merging work to O(n log n) instead of O(n²).",
            hitScore: 2,
            why: "Merges children's data into the larger sibling's structure each time, answering subtree-aggregate queries in O(n log n) instead of O(n²).",
            resource: { label: "USACO Guide: Small-To-Large Merging", url: "https://usaco.guide/plat/merging" },
          },
        ],
      },
    ],
  },
  {
    id: "dp",
    name: "Dynamic Programming",
    blurb: "From knapsack/LIS through bitmask, digit, and tree DP, up to advanced DP-speedup tricks.",
    phases: [
      {
        name: "Foundations",
        topics: [
          {
            id: "dp.recursion-backtracking",
            name: "Recursion & complete search (brute force, backtracking)",
            what: "Explores all possible choices via recursive calls, undoing (backtracking) a choice once its branch is explored — the brute-force baseline every DP is a memoized, faster version of.",
            hitScore: 5,
            why: "Generating every permutation/subset/combination and pruning as you go is the baseline every DP is a faster version of — you can't recognize \"this state repeats\" until you've written the brute-force recursion first.",
            resource: { label: "USACO Guide: Complete Search with Recursion", url: "https://usaco.guide/bronze/complete-rec" },
          },
          {
            id: "dp.dp-basics",
            name: "1D/2D DP basics (knapsack, LIS, LCS)",
            what: "Breaks a problem into overlapping subproblems and caches each subproblem's answer so it's computed once — knapsack (choose items under a capacity), LIS (longest increasing subsequence), and LCS (longest common subsequence) are the classic first examples.",
            hitScore: 5,
            why: "The vocabulary every other DP topic on this list is built from.",
            resource: { label: "cp-algorithms: Introduction to Dynamic Programming", url: "https://cp-algorithms.com/dynamic_programming/intro-to-dp.html" },
          },
          {
            id: "dp.interval-dp",
            name: "Interval / range DP",
            what: "DP over a range [l, r] where the transition tries every way to split the range into two smaller ranges — the pattern behind matrix-chain multiplication and similar ‘optimally split this interval’ problems.",
            hitScore: 4,
            why: "Matrix-chain-multiplication-style DP (optimal split of a range) is a recurring Div2 D pattern.",
            resource: { label: "USACO Guide: Range DP", url: "https://usaco.guide/gold/dp-ranges" },
          },
        ],
      },
      {
        name: "Core",
        topics: [
          {
            id: "dp.bitmask-dp",
            name: "Bitmask DP",
            what: "Uses an integer's bits to represent which elements of a small set have been used so far as the DP state — the standard way to solve small-n ‘visit everything’ problems like the Traveling Salesman Problem.",
            hitScore: 4,
            why: "Encodes a subset as state for small-n \"visit/assign everything\" problems like TSP.",
            resource: { label: "USACO Guide: Bitmask DP", url: "https://usaco.guide/gold/dp-bitmasks" },
          },
          {
            id: "dp.meet-in-the-middle",
            name: "Meet in the middle",
            what: "Splits the input in half, brute-forces all 2^(n/2) outcomes of each half separately, then combines the two halves (often via sorting/binary search) — turns an infeasible 2^n search into a feasible one.",
            hitScore: 3,
            why: "Splits an n-up-to-~40 brute force into two n/2 halves you can each enumerate in 2^(n/2) and combine — turns an infeasible 2^n search into a feasible one without any DP at all.",
            resource: { label: "USACO Guide: Meet In The Middle", url: "https://usaco.guide/gold/meet-in-the-middle" },
          },
          {
            id: "dp.digit-dp",
            name: "Digit DP",
            what: "DP over the digits of a number (most significant first), tracking whether you're still bounded by N's digits so far, to count how many numbers up to N satisfy some digit-based property.",
            hitScore: 3,
            why: "Counts how many numbers up to N satisfy a digit-wise property, without enumerating every number.",
            resource: { label: "USACO Guide: Digit DP", url: "https://usaco.guide/gold/digit-dp" },
          },
          {
            id: "dp.tree-dp",
            name: "Tree DP",
            what: "DP where each node's answer is computed by combining the already-computed answers of its children, in a single post-order DFS pass over the tree.",
            hitScore: 4,
            why: "Nearly every \"optimize something over a tree\" problem reduces to combining DP values from a node's children.",
            resource: { label: "USACO Guide: Tree DP", url: "https://usaco.guide/gold/dp-trees" },
          },
          {
            id: "dp.dp-ds-optimization",
            name: "DP optimized with a data structure (segment tree / BIT transitions)",
            what: "When a DP transition is really a range max/min/sum query over previous states, storing those states in a segment tree or Fenwick tree turns an O(n) transition into O(log n).",
            hitScore: 3,
            why: "Speeds up an O(n²) transition to O(n log n) whenever the transition itself is a range max/min/sum query.",
            resource: { label: "USACO Guide: Point Update Range Sum", url: "https://usaco.guide/gold/PURS" },
          },
        ],
      },
      {
        name: "Advanced",
        topics: [
          {
            id: "dp.sos-dp",
            name: "Sum over subsets (SOS) DP",
            what: "For every bitmask, sums the DP values of all of its submasks by processing one bit position at a time, in O(2^n · n) instead of the naive O(3^n) of checking every mask against every submask directly.",
            hitScore: 2,
            why: "Computes, for every bitmask, an aggregate over all of its submasks in O(2^n · n) instead of the naive O(3^n) — the standard trick once bitmask DP transitions start summing over submasks.",
            resource: { label: "USACO Guide: Sum over Subsets DP", url: "https://usaco.guide/plat/dp-sos" },
          },
          {
            id: "dp.dc-optimization",
            name: "Divide & conquer DP optimization",
            what: "When the optimal split point for a DP transition moves monotonically as the state increases, divide-and-conquer can find every state's optimal split in O(n log n) total instead of checking every split for every state.",
            hitScore: 2,
            why: "Collapses an O(n²) DP to O(n log n) whenever the optimal split point moves monotonically with the state.",
            resource: { label: "cp-algorithms: Divide and Conquer DP", url: "https://cp-algorithms.com/dynamic_programming/divide-and-conquer-dp.html" },
          },
          {
            id: "dp.cht",
            name: "Convex hull trick / Li Chao tree",
            what: "Maintains a lower/upper envelope of linear functions (as a monotonic stack, or a Li Chao segment tree) so that ‘minimize b[j]·x + dp[j] over all j’ can be answered in O(log n) instead of scanning every j.",
            hitScore: 2,
            why: "The standard way to optimize DP transitions shaped like min(dp[j] + b[j]·x) down to O(log n) per query.",
            resource: { label: "cp-algorithms: Convex hull trick and Li Chao tree", url: "https://cp-algorithms.com/geometry/convex_hull_trick.html" },
          },
          {
            id: "dp.knuth-opt",
            name: "Knuth's optimization",
            what: "Like divide-and-conquer optimization, but proven by the cost function satisfying the quadrangle inequality — the optimal split point for state [i,j] is proven to lie between the optimal splits of its neighbors, bounding total work to O(n²).",
            hitScore: 1,
            why: "Another O(n²) → O(n log n) DP speedup, applicable when the cost function satisfies the quadrangle inequality.",
            resource: { label: "cp-algorithms: Knuth's Optimization", url: "https://cp-algorithms.com/dynamic_programming/knuth-optimization.html" },
          },
          {
            id: "dp.slope-trick",
            name: "Slope trick",
            what: "Represents a convex piecewise-linear DP value function as two heaps of its slope-change points, letting common operations (shift, add a cone, take a running min) be done in O(log n) instead of storing the whole function.",
            hitScore: 1,
            why: "Maintains a convex piecewise-linear cost function with a couple of heaps, solving \"minimize Σ|aᵢ − x|\"-style DPs in O(n log n).",
            resource: { label: "USACO Guide: Slope Trick", url: "https://usaco.guide/adv/slope-trick" },
          },
        ],
      },
    ],
  },
  {
    id: "strings",
    name: "Strings",
    blurb: "Hashing and pattern matching up through suffix structures.",
    phases: [
      {
        name: "Foundations",
        topics: [
          {
            id: "strings.string-hashing",
            name: "String hashing (polynomial rolling hash)",
            what: "Hashes every prefix of a string with a rolling polynomial hash, so the hash of any substring — and therefore an equality check between two substrings — is an O(1) computation after O(n) preprocessing.",
            hitScore: 5,
            why: "Turns substring-equality checks into O(1) comparisons after O(n) preprocessing.",
            resource: { label: "cp-algorithms: String Hashing", url: "https://cp-algorithms.com/string/string-hashing.html" },
          },
          {
            id: "strings.kmp",
            name: "KMP / prefix function",
            what: "The prefix function records, for each prefix of a pattern, the length of its longest proper prefix that's also a suffix; KMP uses this to search a text for the pattern in O(n+m) without ever backtracking the text pointer.",
            hitScore: 4,
            why: "O(n+m) exact pattern matching, and the prefix function alone solves string-period problems.",
            resource: { label: "cp-algorithms: Prefix function - KMP", url: "https://cp-algorithms.com/string/prefix-function.html" },
          },
        ],
      },
      {
        name: "Core",
        topics: [
          {
            id: "strings.z-function",
            name: "Z-function",
            what: "For each position i, the Z-function stores the length of the longest common prefix between the string and its suffix starting at i — a different O(n) primitive that solves many of the same pattern-matching problems as KMP.",
            hitScore: 3,
            why: "An alternative to KMP that's often simpler to apply for substring-matching variants and string-comparison tricks.",
            resource: { label: "cp-algorithms: Z-function", url: "https://cp-algorithms.com/string/z-function.html" },
          },
          {
            id: "strings.trie",
            name: "Trie",
            what: "A tree where each edge is a character and each root-to-node path spells a prefix, letting you insert/search strings (or, over binary digits, find max-XOR pairs) in time proportional to string length.",
            hitScore: 4,
            why: "Prefix queries and XOR-trie tricks over a set of strings or numbers.",
            resource: { label: "Topcoder: Using Tries", url: "https://www.topcoder.com/thrive/articles/Using%20Tries" },
          },
          {
            id: "strings.manacher",
            name: "Manacher's algorithm",
            what: "Finds the longest palindrome centered at every position of a string in O(n) total, by reusing previously-computed palindrome radii instead of re-expanding from scratch at each center.",
            hitScore: 3,
            why: "Finds every palindromic substring in O(n), beating the naive O(n²) expand-around-center approach.",
            resource: { label: "cp-algorithms: Manacher's Algorithm", url: "https://cp-algorithms.com/string/manacher.html" },
          },
          {
            id: "strings.aho-corasick",
            name: "Aho-Corasick",
            what: "Builds a trie of many patterns plus ‘failure link’ shortcuts (like KMP's prefix function, generalized to a trie), so a single pass over a text finds every occurrence of every pattern at once.",
            hitScore: 3,
            why: "Matches many patterns against a text in one linear pass — the go-to when you're searching for a whole dictionary of keywords at once.",
            resource: { label: "cp-algorithms: Aho-Corasick algorithm", url: "https://cp-algorithms.com/string/aho_corasick.html" },
          },
        ],
      },
      {
        name: "Advanced",
        topics: [
          {
            id: "strings.suffix-array",
            name: "Suffix array + LCP array (Kasai's algorithm)",
            what: "A sorted array of all of a string's suffixes; paired with the LCP array (longest common prefix between adjacent sorted suffixes, built via Kasai's algorithm), it answers a huge range of substring-comparison and counting questions.",
            hitScore: 2,
            why: "Unlocks a huge class of substring-counting, comparison, and longest-common-substring problems.",
            resource: { label: "cp-algorithms: Suffix Array", url: "https://cp-algorithms.com/string/suffix-array.html" },
          },
          {
            id: "strings.suffix-automaton",
            name: "Suffix automaton",
            what: "The smallest automaton that accepts exactly the substrings of a string, built in O(n) — each state represents a class of substrings sharing the same set of ending positions, giving compact answers to distinct-substring questions.",
            hitScore: 1,
            why: "A linear-size automaton over all substrings of a string — powerful for distinct-substring counting problems.",
            resource: { label: "cp-algorithms: Suffix Automaton", url: "https://cp-algorithms.com/string/suffix-automaton.html" },
          },
          {
            id: "strings.palindromic-tree",
            name: "Palindromic tree (eertree)",
            what: "A structure (eertree) with one node per distinct palindromic substring, built incrementally in O(n), purpose-built for counting or enumerating a string's palindromic substrings.",
            hitScore: 1,
            why: "A structure purpose-built for problems about distinct palindromic substrings.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
        ],
      },
    ],
  },
  {
    id: "greedy",
    name: "Greedy & Sorting",
    blurb: "Sort-then-scan strategies and proving greedy correctness.",
    phases: [
      {
        name: "Foundations",
        topics: [
          {
            id: "greedy.sort-greedy",
            name: "Sorting-based greedy (interval scheduling, activity selection)",
            what: "Sorts the input by some key, then makes a single left-to-right greedy decision per element — the shape of interval scheduling, activity selection, and many similar optimization problems.",
            hitScore: 5,
            why: "A huge share of optimization problems fall to \"sort, then make one greedy pass\" — if you can prove the exchange argument.",
            resource: { label: "Codeforces EDU: courses", url: "https://codeforces.com/edu/courses" },
          },
          {
            id: "greedy.binary-search",
            name: "Binary search (on arrays & on the answer)",
            what: "Repeatedly halves a sorted search space by checking the midpoint, finding a target (or the boundary between ‘feasible’ and ‘infeasible’ answers) in O(log n) instead of scanning every candidate.",
            hitScore: 5,
            why: "Halves the search space every step — the classic form finds a value in a sorted array in O(log n), and \"binary search on the answer\" reuses the same idea to turn \"find the optimal x\" into repeatedly asking \"is x feasible?\".",
            resource: { label: "USACO Guide: Binary Search", url: "https://usaco.guide/silver/binary-search" },
          },
          {
            id: "greedy.two-pointers",
            name: "Two pointers",
            what: "Maintains two indices over a sorted array or string that each move only forward, so a nested O(n²) scan for pairs/windows collapses to a single O(n) pass.",
            hitScore: 5,
            why: "Turns an O(n²) nested scan into O(n) whenever the search window only ever grows in one direction.",
            resource: { label: "USACO Guide: Two Pointers", url: "https://usaco.guide/silver/two-pointers" },
          },
          {
            id: "greedy.coordinate-compression",
            name: "Coordinate compression",
            what: "Sorts a set of values and replaces each with its rank in that sorted order, so a structure that only works on small indices (like a BIT) can be used on values as large as 1e9.",
            hitScore: 4,
            why: "Replaces huge or sparse coordinate values with their sorted rank, so array-indexed structures (BITs, difference arrays) can be used on ranges like 1e9 as if they were size n.",
            resource: { label: "USACO Guide: Custom Comparators and Coordinate Compression", url: "https://usaco.guide/silver/sorting-custom" },
          },
        ],
      },
      {
        name: "Core",
        topics: [
          {
            id: "greedy.exchange-argument",
            name: "Exchange argument (proving greedy correctness)",
            what: "A proof technique that shows a greedy choice is optimal by taking any other (optimal) solution and showing you can swap in the greedy choice without making it worse.",
            hitScore: 3,
            why: "Contest judges won't accept \"it felt right\" — you need to prove your greedy strategy before trusting it under pressure.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
          {
            id: "greedy.pq-greedy",
            name: "Priority-queue greedy (Huffman-style, deadline scheduling)",
            what: "Greedy problems where the ‘best next choice’ changes as you make decisions — a priority queue keeps the current best choice available in O(log n) per step instead of rescanning every candidate.",
            hitScore: 3,
            why: "A large class of greedy problems needs a heap to always grab the provably-best next choice.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
        ],
      },
      {
        name: "Advanced",
        topics: [
          {
            id: "greedy.matroid-greedy",
            name: "Matroid-flavored greedy & exchange proofs",
            what: "A matroid is a set system (generalizing ‘linearly independent vectors’ and ‘forest edges’) where a greedy algorithm is provably optimal; recognizing one explains why a greedy strategy works instead of just observing that it does.",
            hitScore: 1,
            why: "Recognizing matroid structure explains why certain greedy strategies are provably optimal, not just empirically lucky.",
            resource: { label: "Competitive Programmer's Handbook (CSES)", url: "https://cses.fi/book/book.pdf" },
          },
          {
            id: "greedy.heuristic-greedy",
            name: "Randomized / greedy heuristics for NP-hard subtasks",
            what: "For NP-hard subtasks, a greedy or randomized rule that usually finds a very good (if not provably optimal) answer — sometimes the only practical option within a contest's time limit.",
            hitScore: 2,
            why: "Some ICPC problems reward a strong greedy or randomized heuristic even without a full optimality proof.",
            resource: { label: "Codeforces EDU: courses", url: "https://codeforces.com/edu/courses" },
          },
        ],
      },
    ],
  },
  {
    id: "geometry",
    name: "Geometry",
    blurb: "Vectors and orientation tests up through convex hull and half-plane intersection.",
    phases: [
      {
        name: "Foundations",
        topics: [
          {
            id: "geometry.vectors-orientation",
            name: "Vectors, cross/dot product, orientation tests",
            what: "Represents points as 2D vectors; the sign of a cross product tells you whether three points turn clockwise, counterclockwise, or are collinear — the single primitive most other geometry algorithms are built from.",
            hitScore: 4,
            why: "Nearly every geometry problem reduces to the sign of a cross product at some point.",
            resource: { label: "cp-algorithms: Basic Geometry", url: "https://cp-algorithms.com/geometry/basic-geometry.html" },
          },
          {
            id: "geometry.point-segment",
            name: "Point-in-polygon & segment intersection",
            what: "Segment intersection tests whether two line segments cross using orientation signs; point-in-polygon testing (ray casting or winding number) determines whether a point lies inside a polygon boundary.",
            hitScore: 3,
            why: "The two most commonly reused geometry primitives across ICPC problem sets.",
            resource: { label: "cp-algorithms: Check if two segments intersect", url: "https://cp-algorithms.com/geometry/check-segments-intersection.html" },
          },
        ],
      },
      {
        name: "Core",
        topics: [
          {
            id: "geometry.line-sweep",
            name: "Line sweep",
            what: "Conceptually drags a vertical line across all the points/segments/events, processing them left-to-right while maintaining a data structure of what the line currently intersects — turns many O(n²) geometry problems into O(n log n).",
            hitScore: 3,
            why: "Sweeps a line across the plane processing events in order — the standard technique behind segment-intersection detection, rectangle union area, and closest-pair alternatives.",
            resource: { label: "cp-algorithms: Search for a pair of intersecting segments", url: "https://cp-algorithms.com/geometry/intersecting_segments.html" },
          },
          {
            id: "geometry.convex-hull",
            name: "Convex hull (Graham scan / monotone chain)",
            what: "The smallest convex polygon containing a set of points; Graham scan and the monotone chain algorithm both build it in O(n log n) by sorting the points and greedily discarding non-hull ones.",
            hitScore: 3,
            why: "The standard preprocessing step for a huge share of geometry problems — diameter, farthest pair, and more all start here.",
            resource: { label: "cp-algorithms: Convex hull construction", url: "https://cp-algorithms.com/geometry/convex-hull.html" },
          },
          {
            id: "geometry.polygon-area-picks",
            name: "Polygon area & Pick's theorem",
            what: "The shoelace formula computes a polygon's area directly from its vertex coordinates; Pick's theorem then relates that area to the number of lattice (integer-coordinate) points on the boundary and interior.",
            hitScore: 3,
            why: "A closed-form way to compute area (and count lattice points) instead of any kind of numeric integration.",
            resource: { label: "cp-algorithms: Pick's Theorem", url: "https://cp-algorithms.com/geometry/picks-theorem.html" },
          },
          {
            id: "geometry.closest-pair",
            name: "Closest pair of points (divide & conquer)",
            what: "Finds the two closest points in a set in O(n log n) via divide-and-conquer — split the points in half, solve each half, then carefully check only the points near the dividing line.",
            hitScore: 2,
            why: "A classic O(n log n) algorithm that beats the naive O(n²) pairwise distance check.",
            resource: { label: "cp-algorithms: Finding the nearest pair of points", url: "https://cp-algorithms.com/geometry/nearest_points.html" },
          },
        ],
      },
      {
        name: "Advanced",
        topics: [
          {
            id: "geometry.rotating-calipers",
            name: "Rotating calipers",
            what: "Walks two (or more) parallel supporting lines around a convex hull in lockstep, answering diameter, minimum-bounding-box, and farthest-pair queries in linear time without checking every pair.",
            hitScore: 2,
            why: "Powers diameter, minimum bounding box, and farthest-pair queries on a convex hull in linear time.",
            resource: { label: "cp-algorithms: Convex hull construction", url: "https://cp-algorithms.com/geometry/convex-hull.html" },
          },
          {
            id: "geometry.halfplane-intersection",
            name: "Half-plane intersection",
            what: "Each linear constraint (ax+by≤c) defines a half-plane; intersecting many of them at once (via a sweep over their boundary lines) finds the feasible region they all agree on, or proves none exists.",
            hitScore: 1,
            why: "Finds the feasible region defined by many linear constraints at once — the geometric analogue of an LP feasibility check.",
            resource: { label: "cp-algorithms: Half-plane intersection", url: "https://cp-algorithms.com/geometry/halfplane-intersection.html" },
          },
          {
            id: "geometry.circle-geometry",
            name: "Circle geometry (tangents, circle-circle/circle-line intersection)",
            what: "The formulas for where a line and a circle, or two circles, intersect (or are tangent) — the primitives needed once a geometry problem mixes circles in with polygons and lines.",
            hitScore: 2,
            why: "Rounds out your primitive toolkit for the mixed geometry problems that combine lines and circles.",
            resource: { label: "cp-algorithms: Circle-Line Intersection", url: "https://cp-algorithms.com/geometry/circle-line-intersection.html" },
          },
        ],
      },
    ],
  },
  {
    id: "meta",
    name: "Contest Meta-Skills",
    blurb: "The non-algorithmic skills — speed, recognition, and team process — that separate solving-at-home from solving-on-stage.",
    phases: [
      {
        name: "Foundations",
        topics: [
          {
            id: "meta.time-complexity",
            name: "Time complexity & Big-O budgeting",
            what: "Estimating an algorithm's running time as a function of input size (Big-O notation) so you can check it against the time limit and constraints before writing a line of code.",
            hitScore: 5,
            why: "Reading a constraint like n ≤ 10⁵ and knowing it rules out O(n²) is the single most useful reflex in this whole roadmap — every other topic below is really \"a faster way to do X.\"",
            resource: { label: "USACO Guide: Time Complexity", url: "https://usaco.guide/bronze/time-comp" },
          },
          {
            id: "meta.fast-io-templates",
            name: "Fast I/O & a personal template",
            what: "Faster input/output methods (avoiding slow default C++ streams, or using sync_with_stdio(false)) plus a boilerplate file (macros, common includes) you paste at the start of every solution.",
            hitScore: 4,
            why: "A solid template removes boilerplate friction so contest time goes to thinking, not to re-typing scaffolding.",
            resource: { label: "USACO Guide: Fast Input & Output", url: "https://usaco.guide/general/fast-io" },
          },
          {
            id: "meta.reading-problems",
            name: "Reading & parsing problems under time pressure",
            what: "The skill of extracting every constraint, edge case, and required output format from a problem statement correctly and quickly, before committing to an approach.",
            hitScore: 5,
            why: "Misreading one constraint is the single most common source of wasted contest time.",
            resource: { label: "USACO Guide: General resources", url: "https://usaco.guide/general" },
          },
        ],
      },
      {
        name: "Core",
        topics: [
          {
            id: "meta.problem-recognition",
            name: "Problem recognition drills",
            what: "Practicing enough tagged problems that you can identify ‘this needs a segment tree’ or ‘this is a flow problem’ from the problem statement alone, within the first minute of reading it.",
            hitScore: 4,
            why: "ICPC rewards speed — learning to recognize \"this is a segment-tree problem\" within 30 seconds is a trainable skill, not raw talent.",
            resource: { label: "Codeforces EDU: courses", url: "https://codeforces.com/edu/courses" },
          },
          {
            id: "meta.mixed-topic-practice",
            name: "Mixed-topic contest simulation",
            what: "Solving contests (not just topic-sorted problem sets) so you practice figuring out *which* technique applies, not just applying a technique you already know is the right one.",
            hitScore: 4,
            why: "Real contests mix topics freely; practicing techniques in isolation only gets you halfway there.",
            resource: { label: "CSES Problem Set", url: "https://cses.fi/problemset/" },
          },
          {
            id: "meta.team-coordination",
            name: "Team coordination & one-computer rotation",
            what: "The process side of ICPC's 3-person, 1-computer format — deciding who reads problems, who codes, when to swap the keyboard, and how to communicate an idea without the computer.",
            hitScore: 3,
            why: "ICPC is a 3-person, 1-computer format — process discipline (who codes, who reads, when to rotate) wins nearly as much as raw skill.",
            resource: { label: "ICPC official site", url: "https://icpc.global" },
          },
        ],
      },
      {
        name: "Advanced",
        topics: [
          {
            id: "meta.speed-drills",
            name: "Timed speed drills (rating-banded, clock running)",
            what: "Solving problems you already know how to approach, under a running clock, to build raw typing/implementation speed rather than problem-solving ability.",
            hitScore: 3,
            why: "Builds the reflex of solving known-technique problems fast, instead of merely solving them correctly.",
            resource: { label: "CSES Problem Set", url: "https://cses.fi/problemset/" },
          },
          {
            id: "meta.wf-archive",
            name: "ICPC World Finals archive upsolving",
            what: "Working through real ICPC World Finals problem sets, which calibrate you to the harder, more creative problem style of the actual competition you're training for.",
            hitScore: 2,
            why: "World Finals problems calibrate you to the hardest, most creative problem style you'll actually face on stage.",
            resource: { label: "ICPC World Finals Problems", url: "https://icpc.global/worldfinals/problems" },
          },
          {
            id: "meta.post-contest-review",
            name: "Post-contest analysis (editorials + a mistake log)",
            what: "After every contest, reading the editorial for problems you missed and logging *why* you got stuck (wrong idea vs. bug vs. too slow) so the same mistake doesn't repeat.",
            hitScore: 4,
            why: "Reviewing exactly why you got stuck after every contest is the fastest lever you have for improvement.",
            resource: { label: "Codeforces EDU: courses", url: "https://codeforces.com/edu/courses" },
          },
        ],
      },
    ],
  },
];
